#! /bin/bash

## Entradas:
## 		1: direccion IP
##		2: numero de repeticiones
##		3: nombre ficheros salida

echo "Direccion IP: $1"
echo "Numero de repeticiones: $2"
echo "Ficheros de salida: $3-#"

for ((i=1; i<=$2 ; i++))
do
	echo "Realizando ejecuccion $i.........." 
	echo "http://$1/hola.html"
	ab -n 200000 -c 200 http://$1/hola.html >> ./Resultados/$3-$i
	echo "Ejecucion $i terminada"
done
