#! /bin/bash

## Entradas:
## 		1: direccion IP
##		2: numero de repeticiones
##		3: nombre ficheros salida

echo "Direccion IP: $1"
echo "Numero de repeticiones: $2"
echo "Ficheros de salida: $3-#"

for ((i=1; i<=$2 ; i++))
do
	echo "Realizando ejecuccion $i.........." 
	echo "http://$1/hola.html"
	siege -t60S -c 500 http://$1/hola.html 2> ./Resultados/$3-$i.txt
	echo "Ejecucion $i terminada"
done
